### ISSUE TITLE
Incorrect URL in about

### ISSUE THREAD

**Issue by anweshandev** [EJINEROZ/qrcode-gen#1]
The url in the about section should point to [https://qrcode-gene.vercel.app/](https://qrcode-gene.vercel.app/) instead of `https://qrcode-gen-gray.vercel.app/`. Picture has been attached to show the incorrect url.

![SmartSelect_20220603-121303_Chrome](https://user-images.githubusercontent.com/45881338/171801416-3e0a83f6-5b07-4bd3-8e51-30735a17ce14.jpg)

**Comment by EJINEROZ** [comment]
Hi!
Thank you for spotting that issue, I wouldn't have noticed it all along. Anyways I have fixed it.
